version: '3.8'
services:
  data-object:
    image: YOUR_USERNAME/data-object-service:latest
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - AWS_BUCKET=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
  label-detector:
    image: YOUR_USERNAME/label-detector-service:latest
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=