version: '3.8'
services:
  data-object:
    image: YOUR_USERNAME/data-object-service:latest
    container_name: data-object
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - AWS_BUCKET=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
  label-detector:
    image: YOUR_USERNAME/label-detector-service:latest
    container_name: label-detector
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
  cli-client:
    image: YOUR_USERNAME/cli-client:latest
    container_name: cli-client
    profiles: ["client"]
    environment:
      - AWS_BUCKET=
      - DATA_OBJECT_SERVICE_URL=http://data-object:8080/data-object
      - LABEL_DETECTOR_SERVICE_URL=http://label-detector:8081/analyze
    depends_on:
      - data-object
      - label-detector