package ch.heig.amt07;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class Main {
    public static void main(String[] args) throws URISyntaxException, IOException, InterruptedException {
        HttpRequest request = HttpRequest.newBuilder()
                .uri(new URI("http://localhost:8080/analyze/url"))
                .headers("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString("""
                        {
                            "image": "https://www.lausanne.ch/.imaging/mte/lausanne/original/website/lausanne/vie-pratique/nature/patrimoine-arbore/forets/forets-de-vernand/contentAutogenerated/autogeneratedContainer/col1/0/import/forets-vernand-22.2019-10-28-16-54-54.jpg",
                            "maxLabels": 50,
                            "minConfidence": 55.7
                        }"""))
                .build();

        HttpResponse<String> response = HttpClient.newBuilder()
                .build()
                .send(request, HttpResponse.BodyHandlers.ofString());

        String name = "lausanne.jpg.json";
        Path path = Paths.get(name);
        Files.writeString(path, response.body(), StandardCharsets.UTF_8);



        //Files.delete(path); delete le file après coup

        System.out.println(response.body());
    }
}