name: Deploy on Docker Hub - CLI Client
on:
  workflow_run:
    workflows: [Verify & Package - CLI Client]
    branches:
      - main
    types:
      - completed
    paths:
      - "cli-client/**"
      - ".github/workflows/cli-client-deploy.yml"
defaults:
  run:
    working-directory: cli-client
jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          path: cli-client
          context: cli-client/.
          target: production
          file: cli-client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cli-client:latest
