name: Verify & Package - CLI Client
on:
  push:
    branches:
      - main
      - dev
    paths:
      - "cli-client/**"
      - ".github/workflows/cli-client-verify.yml"
defaults:
  run:
    working-directory: cli-client
jobs:
  verify-package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Package with Maven
        run: mvn package -DskipTests
