name: Verify & Package Data Object Service
on:
  push:
    branches:
      - main
      - dev
    paths:
      - "data-object/**"
      - ".github/workflows/data-object-verify.yml"
defaults:
  run:
    working-directory: data-object
jobs:
  verify-package:
    runs-on: ubuntu-22.04
    env:
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2
      TEST_AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      TEST_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TEST_AWS_DEFAULT_REGION: eu-west-2
    steps:
      - name: Checkout Data Object Service
      - uses: actions/checkout@v2
        with:
          path: data-object
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Package with Maven
        run: mvn package -DskipTests
